[package]
name = "rsfetch"
version = "0.1.0"
authors = ["Ash <valleyknight@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
glob = "0.3.0"
log = "0.4.11"
regex = "1"
sedregex = "0.2.4"